### PR TITLE
Gradle 6.6 and verify version on CI

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by hannesa2** [comment]
It seems you have to enable Github action to verify it automatically

image

**Comment by eirnym** [comment]
Hey,

Thank you for a PR

Could you explain why we should drop compatibility with earlier versions of Gradle?

**Comment by hannesa2** [comment]
This pull request is 7 month old, currently I would use `6.8.2` !

It doesn't drop compatibility, it modernize **this** build.
Otherwise it will stuck on a future archeological build. 

Following your doubt, why you don't use this https://github.com/gradle/gradle/releases/tag/v4.3.0 ?

**Comment by eirnym** [comment]
Yeah, it was a tough year. At the end I had to give away my laptop for a hardware replacement.

BTW, The history was what if I use gradle 6.x for a plugin and use 5.6 for a project. But I'll give it a try, give me a minute! 

why 5.6? because plugin is compatible with modern gradle versions.
Why not earlier? because plugins in jsonschema2pogo provide the support for it

**Comment by eirnym** [comment]
it seems to be working!
could you update your PR?

**Comment by hannesa2** [comment]
> could you update your PR?

What should I update ?

**Comment by eirnym** [comment]
Gradle to 6.8.2 :)

**Comment by hannesa2** [comment]
Here you go https://github.com/eirnym/js2p-gradle/pull/14

It will update now and in future your repo, every time when something new will appear

**Comment by hannesa2** [comment]
First merge this, then #14 .... you will see the automatism

**Pull request merged**
